word_list = [
    "design", "graphic", "print", "digital", "storytelling", "innovative", "professional", "content", "flyers", 
    "factsheets", "business", "audiovisual", "production", "recording", "posttreatment", "salesforce", "marketing", 
    "brand", "consistency", "social", "media", "campaigns", "conception", "execution", "curated", "published", 
    "coherence", "translated", "analyses", "strategic", "recommendations", "communication", "moskito", "public", 
    "relations", "green", "lisbon", "portugal", "photography", "basicfit", "brussels", "belgium", "skills", 
    "expertise", "tools", "creative", "cloud", "languages", "english", "portuguese", "german", "french", 
    "solutions", "project", "management", "proven", "complex", "deadlines", "education", "masters", "advertising", 
    "commercial", "dynamic", "experience", "financial", "industry", "specializing", "passionate", 
    "opportunities", "ideas", "forefront", "nordea", "asset", "luxembourg", "manager", "international", 
    "curated", "presided", "maintaining", "plans", "degree", "university", "designer", "portfolio", "clients", 
    "freelance", "illustration", "typography", "layout", "branding", "logos", "posters", "brochures", "websites", 
    "animations", "videos", "photographs", "editing", "software", "photoshop", "premiere", "aftereffects", 
    "illustrator", "indesign", "language", "multilingual", "fluent", "conversational", "beginner", "intermediate", 
    "advanced", "digital", "strategy", "analytics", "email", "automation", "campaign", "optimization", 
    "engagement", "metrics", "budgeting", "forecasting", "scheduling", "coordination", "leadership", 
    "teamwork", "collaboration", "creativity", "innovation", "problem", "solving", "critical", "thinking", 
    "attention", "detail", "organization", "time", "multitasking", "adaptability", "flexibility", "initiative", 
    "motivation", "enthusiasm", "passion", "dedication", "commitment", "integrity", "ethics", "reliability", 
    "punctuality", "professionalism", "confidence", "communication", "presentation", "negotiation", "persuasion", 
    "networking", "relationship", "building", "customer", "service", "feedback", "reviews", "testimonials", 
    "referrals", "loyalty", "retention", "satisfaction", "research", "analysis", "data", "collection", "survey", 
    "interview", "focus", "groups", "report", "writing", "documentation", "proposal", "development", "planning", 
    "implementation", "evaluation", "improvement", "growth", "expansion", "diversification", "penetration", 
    "segmentation", "positioning", "differentiation", "targeting", "acquisition", "conversion", "activation", 
    "monetization", "retention", "referral", "revenue", "profit", "margin", "turnover", "inventory", "supply", 
    "demand", "equilibrium", "elasticity", "substitute", "complement", "goods", "services", "products", "brands", 
    "competitors", "market", "share", "leaders", "followers", "challengers", "niches", "segments", "demographics", 
    "psychographics", "geographics", "behavioral", "factors", "trends", "patterns", "cycles", "seasons", 
    "fluctuations", "variations", "deviations", "anomalies", "outliers", "predictions", "forecasts", "scenarios", 
    "assumptions", "hypotheses", "theories", "models", "frameworks", "concepts", "principles", "laws", "rules", 
    "regulations", "standards", "guidelines", "best", "practices", "case", "studies", "examples", "benchmarks", 
    "metrics", "indicators", "scores", "ratings", "rankings", "reviews", "feedback", "comments", "suggestions", 
    "recommendations", "endorsements", "testimonials", "references", "citations", "sources", "evidence", "proof", 
    "validation", "verification", "authentication", "authorization", "certification", "accreditation", "approval", 
    "recognition", "acknowledgment", "appreciation", "gratitude", "thanks", "praise", "compliments", "rewards", 
    "incentives", "bonuses", "promotions", "raises", "commissions", "royalties", "fees", "salaries", "wages", 
    "benefits", "perks", "privileges", "rights", "responsibilities", "duties", "obligations", "liabilities", 
    "risks", "threats", "opportunities", "strengths", "weaknesses", "advantages", "disadvantages", "pros", "cons", 
    "upsides", "downsides", "gains", "losses", "wins", "defeats", "successes", "failures", "achievements", 
    "accomplishments", "milestones", "breakthroughs", "innovations", "inventions", "discoveries", "insights", 
    "ideas", "concepts", "visions", "dreams", "goals", "objectives", "targets", "priorities", "strategies", 
    "tactics", "actions", "plans", "programs", "projects", "initiatives", "campaigns", "events", "activities", 
    "tasks", "steps", "stages", "phases", "cycles", "processes", "procedures", "methods", "techniques", "tools", 
    "resources", "materials", "equipment", "facilities", "infrastructure", "technology", "hardware", "software", 
    "applications", "platforms", "systems", "networks", "databases", "repositories", "archives", "libraries", 
    "collections", "catalogs", "directories", "lists", "indexes"
]
